### ISSUE TITLE
make `string` equivalent to http://purl.obolibrary.org/obo/IAO_0000028

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/nomen#12]

**Comment by hlapp** [comment]
I would also suggest to either simply replace it, or to work out a better definition and label. As is, it seems to elevate a datatype (`xsd:string`) to a class, which it is already (all `rdf:Datatype` are classes), but I don't think you mean NOMEN_0000028 to be a subclass of `rdf:Datatype`. So if it's not what is it that sets it apart. Presumably, it's being much more than simply a string.
