### ISSUE TITLE
ICZN nonorder

### ISSUE THREAD

**Issue by mdoering** [SpeciesFileGroup/nomen#18]
I cannot find any example of rank `ICZN nonorder`
Maybe a misspelled nanorder?

**Comment by mjy** [comment]
Nanorder is "real" IIRC (but see below).  Likely we just did not come across it yet. @proceps should we add?

There is no governance of ranks really in the ICZN, beyond the concepts of species, genus, family group names, so anyone can make any names for ranks they want, and order them any way they want.  This is obviously problematic.

**Comment by mdoering** [comment]
Nanorder is listed https://en.wiktionary.org/wiki/nanorder and https://en.wikipedia.org/wiki/Taxonomic_rank#All_ranks

And it seems to be used in palaeo taxa: http://taxonomicon.taxonomy.nl/TaxonTree.aspx?id=1674371&src=5617

But does Nonorder exist?

**Comment by mjy** [comment]
If someone used it, on purpose I suppose, it exists.

**Comment by mdoering** [comment]
Do you have any example where its being used?

**Comment by proceps** [comment]
@mjy  we have nanorder. 
@mdoering nonorder, I think is either a misspelling of nanorder or non- which is 'non' to indicate a not ordered category.

I really like botanical approach. All ranks are defined by combination of sub- and super- prefixes. So you can have a supersubsuperorder or subsubsubfamily. It looks ugly, but there is no speculation what is the order of the ranks. We did our preferred ordering in TW, which is probably not universal. We can of cause include a parent rank for each rank in NOMEN. All additional ranks could be included into NOMEN by special request. I do not see any reason to try to include everything what people historically used.

**Comment by proceps** [comment]
It was just a misspelling of nanorder. Fixed it
