### ISSUE TITLE
ICN horticulture or ICNCP

### ISSUE THREAD

**Issue by mdoering** [SpeciesFileGroup/nomen#19]
Should there be a [ICNCP code](https://www.ishs.org/news/icncp-international-code-nomenclature-cultivated-plants-9th-edition) on its own right instead of the ICN horticulture class?

**Comment by mjy** [comment]
@proceps, thoughts?

@mdoering from your experience are there different fields (or even is there a different focus on what fields are used) when you get names coming in from ICNCP providers?

We'll have to look at how different the rules are in there, if its essentially subclassing ICN, etc.

**Comment by mdoering** [comment]
Cultivar names have their own syntax and don't represent a botanical name in the sense of ICN, so subclassing does not seem right to me. They do built on botanical names though, but it is rather through composition that subclassing ;) They also have their own ranks (grex, cultivar group, convariety) and even a cultivar name given in quotes.

**Comment by proceps** [comment]
Well, ICNCP is an independent code of nomenclature, but at the same time, it is cross reference ICN a lot. A typical name of a cultivar is something like this:
Malus domestica 'James Grieve'
Where the first part of the name is a Latin name governed by ICN, It could be a species or genus group name, or a name of a hybrid.
Second part is a name of a cultivar. There are also some groups of cultivars.
I can definitely include the Code in the NOMEN, but I do not see any practical reasons to include this into TaxonWorks, unless somebody really want to go in this direction. This is not included in CoL. Do you really want to cover this in CoL+?

**Comment by mdoering** [comment]
I'm just wondering. We include ICNCP in our code enumeration since the very beginning of GBIF. But I doubt we get lots of cultivar names. There are a few though, so it is not unused.

**Comment by mdoering** [comment]
I doubt people would supply cultivar names with a NOMEN status though. So in this regard I don't care much. For the sake of completeness it would obviously be good to have it

**Comment by mdoering** [comment]
Dyntaxa, which is a source for the GBIF Backbone, seems to include them:

https://www.gbif.org/species/search?dataset_key=de8934f4-a136-481c-a87a-b0b202b80a31&name_type=CULTIVAR&advanced=1

**Comment by mjy** [comment]
@proceps for the record NOMEN is %100 not == TaxonWorks.  We can add as many things that follow the ideas in NOMEN as we want, as long as they try to do so logically/etc. following the organizing ideas we initially came up with.  We can use any of the bits we do/not want in TaxonWorks as we see fit.

**Comment by proceps** [comment]
@mjy I am on the same page. As long as somebody is ready to use it, I am ready to modify NOMEN.

**Comment by proceps** [comment]
ICNCP added to NOMEN
