### ISSUE TITLE
Update NOMEN to include combination, original combination and typification properties

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/nomen#21]
@proceps we seem to be out of sync in NOMEN with the model we came up with here?  Should we add the object properties to reflect what we have in TaxonWorks.  Remind me if we had some reason not to?

**Comment by proceps** [comment]
I will take a look into it.

**Comment by mjy** [comment]
Thanks. Make sure to pull, I made some tweaks to very top level classes.

**Comment by proceps** [comment]
@mjy your changes resulted in duplication of classes is it intended?
Typification etc. are included in NOMEN

**Comment by mjy** [comment]
> @mjy your changes resulted in duplication of classes is it intended?

Did I mess something up?  Example?

**Comment by proceps** [comment]
fixed it
